joint_pd_controller:
    type: fr3_ros/JointPDController
    urdf_filename: /home/bolun/bolun_ws/src/franka_ros_bolun/franka_example_controllers/fr3.urdf
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 700.0
        - 400.0
        - 500.0
        - 600.0
        - 5000.0
        - 3000.0
        - 5000.0
    d_gains:
        - 60.0
        - 30.0
        - 40.0
        - 20.0
        - 500.0
        - 400.0
        - 1000.0
    radius: 0.1
    acceleration_time: 2.0
    vel_max: 0.15
    publish_rate: 10.0
    coriolis_factor: 1.0

task_joint_pd_controller:
    type: fr3_ros/TaskJointPDController
    urdf_filename: /home/bolun/bolun_ws/src/franka_ros_bolun/franka_example_controllers/fr3.urdf
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 700.0
        - 400.0
        - 500.0
        - 600.0
        - 5000.0
        - 3000.0
        - 5000.0
    d_gains:
        - 60.0
        - 30.0
        - 40.0
        - 20.0
        - 500.0
        - 400.0
        - 1000.0
    radius: 0.1
    acceleration_time: 2.0
    vel_max: 0.15
    publish_rate: 10.0
    coriolis_factor: 1.0

qp_controller:
    type: fr3_ros/QPController
    urdf_filename: /home/bolun/bolun_ws/src/franka_ros_bolun/franka_example_controllers/fr3.urdf
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    tk_gains:
        - 1000.0
        - 1000.0
        - 1000.0
        - 1500.0
        - 1500.0
        - 2000.0
    td_gains:
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
    epsilon: 0.3

waypoint_controller:
    type: fr3_ros/WaypointController
    urdf_filename: /home/bolun/bolun_ws/src/franka_ros_bolun/franka_example_controllers/fr3.urdf
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    tk_gains:
        - 1000.0
        - 1000.0
        - 1000.0
        - 1500.0
        - 1500.0
        - 2000.0
    td_gains:
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
    epsilon: 0.01

waypoint_cbf_controller:
    type: fr3_ros/WaypointCBFController
    urdf_filename: /home/bolun/bolun_ws/src/franka_ros_bolun/franka_example_controllers/fr3.urdf
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    tk_gains:
        - 1000.0
        - 1000.0
        - 1000.0
        - 1500.0
        - 1500.0
        - 2000.0
    td_gains:
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
    epsilon: 0.01

cbf_controller:
    type: fr3_ros/CBFController
    urdf_filename: /home/bolun/bolun_ws/src/franka_ros_bolun/franka_example_controllers/fr3.urdf
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    tk_gains:
        - 1000.0
        - 1000.0
        - 1000.0
        - 1500.0
        - 1500.0
        - 2000.0
    td_gains:
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
        - 20.0
    epsilon: 0.01